apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testdeployment
  name: testdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testdeployment
    spec:
      containers:
      - image: 834829128384.dkr.ecr.us-east-2.amazonaws.com/demorepo:latest
        name: demorepo
        resources: {}
status: {}